spring:
  application:
    name: KusHouse-backend
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jwt:
    secret: "testajfhahsfkasfkajsfadsfnalralksfjlajstknfkljasfnakljfkasnrksnfksnka"

  config:
    import: mysql.yml


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/kusHouse?useSSL=false&serverTimezone=Asia/Seoul
#    username: root
#    password: 1234, my-secret-pw
#    driver-class-name: com.mysql.cj.jdbc.Driver
